ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('authenticate/',include('authentication.urls',namespace='authenticate')),
    path('authenticate/',include('django.contrib.auth.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('orders.urls',namespace='cart')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('',views.CartView.as_view(),name='view_cart'),
    path('add/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:pk>/',views.CartItemDelete.as_view(),name='remove'),
    path('order/',views.place_order,name='order'),
    path('user/orders/',views.UserOrderList.as_view(),name='order_user'),
    path('order/<int:pk>/',views.OrderDetail.as_view(),name='order_detail')
]

ecommerce/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('new/',views.CreateProduct.as_view(),name='create'),
    path('',views.ListProduct.as_view(),name='all'),
    path('detail/<int:pk>/',views.ProductDetail.as_view(),name='single'),
    path('category/<int:pk>/',views.CategoryProduct.as_view(),name="category_product"),
]

ecommerce/shop/models.py
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField 
# Create your models here.

class ProductGallery(models.Model):
    image = models.ImageField()

class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to ='products/')
    description = RichTextField()
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(null=True)
    view_count = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

    def increase_view_count(self):
        if self.view_count is None:
            self.view_count = 1
        else:
            self.view_count += 1
        self.save()
        
    def get_absolute_url(self):
        return reverse("shop:all")

    class Meta:
        ordering = ['-created_at']


class ProductGallery(models.Model):
    images = models.ImageField(upload_to ='products/')

ecommerce/shop/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from . import models
# Create your views here.
class CreateProduct(LoginRequiredMixin,generic.CreateView):
    model = models.Product
    fields = ('name','image','description','price','quantity','category')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ListProduct(generic.ListView):
    model = models.Product

class ProductDetail(generic.DetailView):
    model = models.Product
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.increase_view_count()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

class CategoryProduct(generic.TemplateView):
    template_name = "shop/category_product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = models.Product.objects.filter(category=self.kwargs.get('pk'))
        context["products"] = product
        return context
    

ecommerce/templates/shop/_product.html
<div class="products">
    {% for product in object_list %}
    <div class="product-card">
        <div class="product-list-container">
        <a class='list-product-item' href="{% url 'shop:single' pk=product.pk%}" >
            <img src="{{product.image.url}}" alt="Product Name">
            <h3 class="product-title">{{product.name}}</h3>
            <p class="product-price">Rs.{{product.price}}</p>
             {% comment %} <p class="product-view-count">{{product.view_count}}</p> {% endcomment %}
        </a>
        </div>
    </div>
    {% endfor %}
</div>

ecommerce/templates/shop/category_product.html
{% include "base/base.html" %}
{% load static%}

{% block body_content %}

<div class="products">
{% for product in products %}
    <div class="product-card">
        <div class="product-list-container">
            <a class='list-product-item' href="#" >
                <img src="{{product.image.url}}" alt="Product Name">
                <h3 class="product-title">{{product.name}}</h3>
                <p class="product-price">Rs.{{product.price}}</p>
            </a>
        </div>
    </div>
{% empty %}
<p>No item for this category yet!!</p>
{% endfor %}
</div>

{% endblock  %}

ecommerce/templates/shop/product_detail.html
{% extends "base/base.html" %}

{% block body_content %}

<div class="row">
    <div class="col-sm-4" id="product-detail-image">
        <div class="product-image">
            <img src="{{product.image.url}}" alt="Product Name" class="img-fluid">
        </div>
    </div>

    <div class="col-sm-8">
        <div class='product-title'>
            <span>{{product.name}}</span>
        </div>
        <div class="product-price">
            <span>Rs.{{product.price}}</span>
            <hr id="product-hr">
        </div>
        <div class='product-description' >
            <h4>Description:</h4>
            {{product.description| safe}}
            <hr id="product-hr">
        </div>
        <div id='product-quantity'>
            <h5>Available: {{product.quantity}}</h5>
        </div>
        <div class="product-quantity">
            <h5>QTY: 
            <input id="quantity" type="number" value="1" />
            </h5>
        </div>
        <div class="row-container">
            <button class='shop-now'>
                <span>Buy now</span>
            </button>
            <button class='add-to-cart'>
                <a href="{% url 'cart:add_to_cart' product.id %}">
                    <span>Add to cart</span>
                </a>
            </button>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/templates/shop/product_form.html
{% extends "base/base.html" %}
{% load bootstrap3 %}

{% block body_content %}
<form action="{% url 'shop:create' %}" method="POST" id='productForm' enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-primary btn-large' value="Create">
</form>
{% endblock %}

ecommerce/templates/shop/product_list.html
{% extends "base/base.html" %}
{%load static%}

{% block body_content %}
{% include "shop/_product.html" %}

{% endblock %}