ecommerce/authentication/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path
from . import views

app_name = 'authenticate'

urlpatterns = [
    path('login/',auth_view.LoginView.as_view(template_name='authentication/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('detail/<int:pk>/',views.CustomUserDetail.as_view(),name='user_detail'),
    path('update/<int:pk>/',views.CustomUserUpdate.as_view(),name='user_update'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('authenticate/',include('authentication.urls',namespace='authenticate')),
    path('authenticate/',include('django.contrib.auth.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('orders.urls',namespace='cart')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('',views.CartView.as_view(),name='view_cart'),
    path('add/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:pk>/',views.CartItemDelete.as_view(),name='remove'),
    path('order/',views.place_order,name='order'),
    path('user/orders/',views.UserOrderList.as_view(),name='order_user'),
    path('order/<int:pk>/',views.OrderDetail.as_view(),name='order_detail')
]

ecommerce/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('new/',views.CreateProduct.as_view(),name='create'),
    path('',views.ListProduct.as_view(),name='all'),
    path('detail/<int:pk>/',views.ProductDetail.as_view(),name='single'),
    path('category/<int:pk>/',views.CategoryProduct.as_view(),name="category_product"),
]

ecommerce/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- font awesome icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>
    {% include 'base/navbar.html' %}

    <div class="container content" id='content'>
        {% block body_content %}
    
        {% endblock %}
    </div>
    
</body>
</html>

ecommerce/templates/base/index.html
{% extends "base/base.html" %}
{% load static %}

{% block body_content %}

<!--Carousel for Ads-->
<div class="row row-no-gutters">
  <div class="col-sm-4" id="categoryContainer">
        <h2>Category</h2>
            {% for cat in categories %}
            <a href="{% url 'shop:category_product' pk=cat.pk %}" class="category-product">
                <p>{{cat.name}}</p>
            </a>
            {% endfor %}
  </div>

  <div class="col-sm-8">
    <div class="carouselAds-container">
        <div id="carouselAds" class="carousel carousel-dark slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselAds" data-slide-to="0" class="active"></li>
                <li data-target="#carouselAds" data-slide-to="1"></li>
                <li data-target="#carouselAds" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                {% for product in products %}
                <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" id="slide{{ forloop.counter }}">
                <img src="{{product.image.url}}" class="d-block w-100" alt="...">
                </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselAds" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselAds" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
  </div>
</div>


<!--Latest Products-->
<div class="latest-products-container">
    <h3 class='text-center'>Latest Products</h3>
    <hr>

    <div id="carouselLatestProducts" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
               <div class="products">
                    {% for product in products %}
                    <div class="product-card">
                        <div class="product-list-container">
                        <a class='list-product-item' href="{% url 'shop:single' pk=product.pk%}" id="unstyled-link">
                            <img src="{{product.image.url}}" alt="Product Name">
                            <h3 class="product-title">{{product.name}}</h3>
                            <p class="product-price">Rs.{{product.price}}</p>
                        </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>    
        </div>
    </div>
</div>


<!--Recommended for You-->
<div class="recommendation-container">
    <h3 class='text-center'>Recommended For You</h3>
    <hr>

    <div id="carouselLatestProducts" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="products">
                    {% for product in products %}
                    <div class="product-card">
                        <div class="product-list-container">
                        <a class='list-product-item' href="{% url 'shop:single' pk=product.pk%}" id="unstyled-link">
                            <img src="{{product.image.url}}" alt="Product Name">
                            <h3 class="product-title">{{product.name}}</h3>
                            <p class="product-price">Rs.{{product.price}}</p>
                        </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<!--Most Search-->
<div class="most-search-container">
    <h3 class='text-center'>Most Search</h3>
    <hr>

    <div id="carouselLatestProducts" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="products">
                    {% for product in product_most_search %}
                    <div class="product-card">
                        <div class="product-list-container">
                        <a class='list-product-item' href="{% url 'shop:single' pk=product.pk%}" id="unstyled-link">
                            <img src="{{product.image.url}}" alt="Product Name">
                            <h3 class="product-title">{{product.name}}</h3>
                            <p class="product-price">Rs.{{product.price}}</p>
                            <p class="product-price">Search Count: {{product.view_count}}</p>
                        </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{%url 'home' %}">LOGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
    </div>
  <div class="topnav-right">
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:all' %}">Shop <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'shop:create' %}">Add Product</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:view_cart' %}">{{cart_item_count}}<span class='fas fa-shopping-cart'></span></a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fas fa-user"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'authenticate:user_detail' pk=user.pk %}">view Profile</a>
              <a class="dropdown-item" href="{% url 'authenticate:user_update' pk=user.id %}">Edit Profile</a>
              <a class="dropdown-item" href="{% url 'cart:order_user'%}">My Orders</a>
              <a class="dropdown-item" href="{% url 'authenticate:logout' %}">Logout</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:logout' %}">Log Out</a></li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:signup' %}">Sign Up</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>

ecommerce/templates/base/thanks.html
{% extends 'base/base.html' %}

{% block body_content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock  %}