ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('authenticate/',include('authentication.urls',namespace='authenticate')),
    path('authenticate/',include('django.contrib.auth.urls')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('orders.urls',namespace='cart')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('',views.CartView.as_view(),name='view_cart'),
    path('add/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:pk>/',views.CartItemDelete.as_view(),name='remove'),
    path('order/',views.place_order,name='order'),
    path('user/orders/',views.UserOrderList.as_view(),name='order_user'),
    path('order/<int:pk>/',views.OrderDetail.as_view(),name='order_detail')
]

ecommerce/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('new/',views.CreateProduct.as_view(),name='create'),
    path('',views.ListProduct.as_view(),name='all'),
    path('detail/<int:pk>/',views.ProductDetail.as_view(),name='single'),
    path('category/<int:pk>/',views.CategoryProduct.as_view(),name="category_product"),
]

ecommerce/orders/models.py
from django.db import models

from shop.models import Product
from authentication.models import CustomUser

# Create your models here.
class Cart(models.Model):
    cart_count = models.PositiveIntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    product_quantity = models.IntegerField(default=1)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE, null=True, related_name='user_cart')

    def __str__(self):
        return str(self.cart_count)

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

# class PaymentMethod(models.Model):
#     name = models.CharField(max_length=256)

#     def __str__(self):
#         return self.name
    

class Order(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE, null=True)
    total = models.PositiveIntegerField()
    status = models.CharField(max_length=256, default='pending')
    shipping_address = models.CharField(max_length=256, null=True)
    phone_number = models.PositiveIntegerField()
    payment_method = models.CharField(max_length=256,default="Cash On Delivery")
    user = models.ForeignKey(CustomUser,related_name='orders',on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.payment_method

    def change_status(self):
        self.status = 'Delivered'
        self.save()

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']
    
    

ecommerce/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ("shipping_address","phone_number","payment_method")

ecommerce/orders/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import Http404
from django.views import generic

from authentication.models import CustomUser

from .models import Cart, Order

from shop.models import Product

from .forms import OrderForm

# Create your views here.

#Cart
@login_required
def add_to_cart(request,product_id):
    product = get_object_or_404(Product,pk=product_id)

    try:
        existing_item = Cart.objects.get(product=product, user=request.user)
        existing_item.product = product
        existing_item.product_quantity += 1
        existing_item.user = request.user
        existing_item.save()
    except Cart.DoesNotExist:
        new_item = Cart.objects.create(product=product,user=request.user, product_quantity=1)
        new_item.save()
    return redirect('cart:view_cart')

class CartView(LoginRequiredMixin,generic.ListView):
    model = Cart
    template_name = "orders/view_cart.html"
    context_object_name = 'cart'

class CartItemDelete(LoginRequiredMixin,generic.DeleteView):
    model = Cart
    success_url = reverse_lazy('cart:view_cart')

    def get(self, request, *args, **kwargs):
      return self.delete(request, *args, **kwargs)



#Order
@login_required
def place_order(request):
    cart = get_object_or_404(Cart,user=request.user)

    total = cart.product.price * cart.product_quantity

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.cart = cart
            new_order.user = request.user
            new_order.total = total
            new_order.save()
            return redirect("cart:order_user")
    else:
        form = OrderForm()
    return render(request,'orders/order_form.html',{'form':form, 'total':total})

class UserOrderList(LoginRequiredMixin,generic.ListView):
    model = Order
    template_name = 'orders/user_order.html'
    context_object_name = 'order_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders"] = Order.objects.filter(user=self.request.user)
        return context
    
class OrderDetail(LoginRequiredMixin,generic.DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders"] = Order.objects.filter(user=self.request.user)
        return context

    



    
    

ecommerce/templates/orders/order_detail.html
{% extends "base/base.html" %}

{% block body_content %}
{% for order in orders %}
<h5>Order No: {{order.id}}</h5>
<p>Placed on {{order.created_at}}</p>
<div class="shipping-detail">
    <h5>Ship and bill to:</h5>
    <h6>{{user.email}}</h6>
    <h6>{{order.user.first_name}} {{order.user.last_name}}</h6>
    <h6>{{order.phone_number}}</h6>
    <p>{{order.shipping_address}}</p>
    <hr id="product-hr">
    </div>
<div class="container">
    <div class="row" id="orders">
      <div class='col-md-4'>
        <div class="product-image">
            <img src="{{order.cart.product.image.url}}" alt="Product Name" class="img-fluid">
        </div>
      </div>  
      
      <div class="col-sm-8">
        <div class='product-title'>
            <span>{{order.cart.product.name}}</span>
        </div>
        <div class="product-price">
            <span>Rs.{{order.cart.product.price}}</span>
        </div>
        <div class='product-quantity' >
            x{{order.cart.product_quantity}}
        </div>
        <div id='order-total'>
            <h5>Total: {{order.total}}</h5>
        </div>
        <div class="payment-method">
            <p>Paid by: {{order.payment_method}}</p>
        </div>
        {% comment %} <div id="order-status">
            <h6>{{order.status}}</h6>
        </div> {% endcomment %}
    </div>
    <hr id="product-hr">
</div>
{% endfor %}
{% endblock %}

ecommerce/templates/orders/order_form.html
{% include "base/base.html" %}
{% load bootstrap3 %}

{% block my_content %}

<form action="{% url 'cart:order' %}" method="POST" id='orderForm'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="total">
        <p>Total Amount: <strong>{{total}}</strong></p>
    </div>
    <input type="submit" class='btn btn-primary btn-large' value="Place Order">
</form>
{% endblock %}

ecommerce/templates/orders/user_order.html
{% include "base/base.html" %}

{% block body_content %}

{% for order in orders %}
<h5>Order No: {{order.id}}</h5>
<p>Placed on {{order.created_at}}</p>
<a href="{% url 'cart:order_detail' pk=order.pk%}" id="order-detail">
<div class="container">
        <div class="row" id="orders">
            <div class='col-md-4'>
                <div class="product-image">
                    <img src="{{order.cart.product.image.url}}" alt="Product Name" class="img-fluid">
                </div>
            </div>  
      
        <div class="col-sm-8">
            <div class='product-title'>
                <span>{{order.cart.product.name}}</span>
            </div>
            <div class="product-price">
                <span>Rs.{{order.cart.product.price}}</span>
            </div>
            <div class='product-quantity' >
                x{{order.cart.product_quantity}}
                <hr id="product-hr">
            </div>
            <div id="order-status">
                <h6>{{order.status}}</h6>
            </div>
            <div id='order-total'>
                <h5>Total: {{order.total}}</h5>
            </div>
        </div>
</div>
</a>

{% endfor %}

{% endblock %}

ecommerce/templates/orders/view_cart.html
{% extends "base/base.html" %}

{% block body_content %}

<h2 style="text-align: center;">My Cart</h2>
<hr>

<table class='table table-bordered'>
    <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            {% comment %} <th>Total</th> {% endcomment %}
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.product.price }}</td>
                <td>{{ item.product_quantity }}</td>
                <td><button class='btn btn-dark'><a href="{% url 'cart:remove'  pk=item.pk %}" id='remove-button'>Remove</a></button></td>
            </tr>
        {% empty %}
        <p>Your cart is empty.</p>
        {% endfor %}
    </tbody>
</table>
<button class="btn btn-dark" id="place-order"><a href="{% url 'cart:order' %}">Place Order</a></button>


{% endblock %}